/**
 * Generate the two derived artifacts from `src/prompts.json`:
 *
 *   - `preset/plugin/prompts.mjs` — the prompt data as an ES module the preset's
 *     plugin imports. A preset row resolves *relative* specifiers against the
 *     preset directory, so shipping this file beside the plugin is what makes
 *     the preset self-contained.
 *   - `dynamic/host.js` — the same plugin as a plain-JavaScript Cordis Host half
 *     for `cordis_define` / `cordis_run`, which cannot import anything and must
 *     reach tools through `harness.defineTool` + `harness.registerTool`.
 *
 * The dynamic half is *derived from the same source module* rather than
 * re-implemented, so the two can never drift: the transform swaps the module
 * wrapper for a returned Plugin object and routes tool registration through the
 * dynamic harness. It asserts every expected pattern, so a source edit that
 * breaks the derivation fails the build instead of silently emitting a stale
 * runtime half.
 *
 * Usage: node scripts/build.mjs
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const PROJECT = resolve(HERE, '..')

const GENERATED = 'GENERATED by scripts/build.mjs — do not edit by hand; run `npm run build`.'

/**
 * Replace exactly one occurrence of `needle`, asserting it was present.
 * @param {string} source - the text to rewrite.
 * @param {string | RegExp} needle - the pattern that must match.
 * @param {string} replacement - its replacement.
 * @param {string} label - the build step, for the failure message.
 * @returns {string} the rewritten text.
 */
function replaceOnce(source, needle, replacement, label) {
  const before = source
  const after = typeof needle === 'string' ? source.replace(needle, replacement) : source.replace(needle, replacement)
  if (after === before) throw new Error(`build: ${label} did not match its expected source pattern`)
  return after
}

const prompts = JSON.parse(readFileSync(resolve(PROJECT, 'src/prompts.json'), 'utf8'))
const moduleSource = readFileSync(resolve(PROJECT, 'preset/plugin/security-review.mjs'), 'utf8')

// ── preset/plugin/prompts.mjs ───────────────────────────────────────────────

const promptsModule = `// ${GENERATED}\n`
  + `// Source: src/prompts.json (extracted from VulnHuntr vulnhuntr/prompts.py, sha256 ${prompts.sourceSha256}).\n\n`
  + `export const PROMPTS = ${JSON.stringify(prompts, null, 2)}\n`
const promptsPath = resolve(PROJECT, 'preset/plugin/prompts.mjs')
mkdirSync(dirname(promptsPath), { recursive: true })
writeFileSync(promptsPath, promptsModule, 'utf8')

// ── dynamic/host.js ─────────────────────────────────────────────────────────

let body = moduleSource
body = replaceOnce(body, /^import \{ PROMPTS \} from '\.\/prompts\.mjs'\n/m, '', 'drop the prompt-data import')
body = replaceOnce(body, /^export const name = /m, 'const name = ', 'unwrap the name export')
body = replaceOnce(body, /^export const inject = /m, 'const inject = ', 'unwrap the inject export')
body = replaceOnce(body, /^export function apply\(ctx\)/m, 'function apply(ctx)', 'unwrap the apply export')
body = replaceOnce(
  body,
  'ctx.effect(() => ctx.tools.register(tool), `security-review.tool(${tool.name})`)',
  'ctx.effect(() => harness.registerTool(ctx, harness.defineTool(tool)), `security-review.tool(${tool.name})`)',
  'route tool registration through the dynamic harness',
)

const dynamicSource = `// ${GENERATED}\n`
  + '//\n'
  + '// Dynamic Cordis Host half for this plugin. Paste the whole file into\n'
  + "// `cordis_define` as `code.host`, then activate the returned package with\n"
  + '// `cordis_run`. It needs no approval flow of its own and no preset install.\n'
  + '//\n'
  + `// Derived from preset/plugin/security-review.mjs (prompt data sha256 ${prompts.sourceSha256}).\n\n`
  + `const PROMPTS = ${JSON.stringify(prompts)}\n\n`
  + body
  + '\nreturn { name, inject, apply }\n'
const dynamicPath = resolve(PROJECT, 'dynamic/host.js')
mkdirSync(dirname(dynamicPath), { recursive: true })
writeFileSync(dynamicPath, dynamicSource, 'utf8')

console.log(`wrote ${promptsPath} (${promptsModule.length} chars)`)
console.log(`wrote ${dynamicPath} (${dynamicSource.length} chars)`)
